atomist/docs

- docs/quick-starts/rug-cli.md
because "better understand Atomist" is our goal, not theirs
> Focus on what the user wants to do

- .atomist.yml
- .atomist/editors/UpdateCopyright.rug
- .atomist/manifest.yml
- .atomist/templates/UpdateCopyrightTemplate.vm
- .atomist/tests/UpdateCopyright.rt
As it happens, this editor makes a change in only one place. Still, it could be applied to multiple repos, that would be useful, right?
I don't intend to publish these editors, yet. It can run in local mode inside its own repo.
> Update copyright editor

- docs/quick-starts/index.md
- docs/quick-starts/rug-typescript.md
- mkdocs.yml
Added initial TypeScript quick start documentation.
> Typescript quick start

- docs/quick-starts/rug-cli.md
- docs/quick-starts/rug-typescript.md
- docs/reference-docs/rug/escape/rug-javascript.md
- docs/reference-docs/rug/rug-cli-commands.md
- docs/reference-docs/rug/rug-conventions.md
- docs/reference-docs/rug/rug-editors.md
- docs/reference-docs/rug/rug-generators.md
- docs/reference-docs/rug/rug-predicates.md
- docs/reference-docs/rug/rug-tests.md
- docs/rug/rug-cli/rug-cli-install.md
- docs/rug/rug-lifecycle.md
Let's make sure snippets are coloured whenever possible.
I will add support for Rug next but I've prepared the matching already here.
> Colouring snippets

- docs/reference-docs/rug/extensions/index.md
- docs/reference-docs/rug/index.md
- docs/reference-docs/rug/rug-custom-types.md
- docs/reference-docs/rug/rug-microgrammars.md
- docs/reference-docs/rug/rug-path-expressions.md
- mkdocs.yml
Also prepares the ground to write up an introduction to path expressions in the reference documentation.
> Microgrammarinitial

- .atomist/editors/SimpleSampleEditor.ts
- .atomist/manifest.yml
- .atomist/package.json
- .atomist/tests/MyFirstEditor.rt
- .atomist/tsconfig.json
- docs/quick-starts/rug-typescript.md
***Please merge only when 0.12.0 is released***
- Use proper code highlighting keywords
- Update for 0.12.0
- Add editors/samples in to repo itself - we could link to these too?
> Update TS documentation for 0.12.0

- docs/rug/rug-cli/rug-cli-install.md
> Document Docker usage

- docs/capabilities.md
- docs/concepts.md
- docs/stylesheets/extra.css
- docs/user-guide/rug/commands.md
- docs/user-guide/rug/path-expressions.md
- mkdocs.yml
Flesh out the capabilities page in overview.  It needs review.
Uncomment commands page in user guide.  Minor cleanup.
More towards #86
> Initial submission of capabilities copy

- docs/getting-started/connect-atomist-to-github.md
- docs/getting-started/invite-atomist-to-slack.md
- docs/user-guide/permissions/github.md
- docs/user-guide/permissions/index.md
- docs/user-guide/permissions/slack.md
- mkdocs.yml
document the slack and github scopes requested by Atomist
> add user permissions splainer

- docs/user-guide/rug/commands.md
- docs/user-guide/rug/editors.md
- docs/user-guide/rug/generators.md
Following our discussion of yesterday, I have started the work of moving to Spring-based samples. If the content suits you guys, I'll follow on that path.
> Spring boot Rugs

- docs/user-guide/rug/commands.md
One subtle but important change is making the difference between `commands` and `Command Handlers` clear. Commands are sent by the user and handled by Command Handlers. Commands are declared in Command Handlers. 
Relates to #105
> Minor fixes some rewording for clarity on Command Handlers

- docs/user-guide/rug/lifecycle.md
This works with recent changes of rug, the cli and the various editors.
> Update lifecycle page to most recent changes

- docs/user-guide/rug/handler-tests.md
Adding content on handler testing--not yet linked from anywhere else.
> Added handler test content

- docs/developer/client.md
- docs/developer/create.md
> link to spring5 generator

- docs/developer/quick-start.md
There was some discussion about moving this up one level and out of the developer group. But I didn't want to make changes and move it at the same time. It may be okay where it is, there are several links that would need to change.
> remove some duplication between pages around events and commands

- docs/user/index.md
- mkdocs.yml
Removed German style capitalization, other copy edits.
> More copy edits

- docs/developer/commands.md
pegged to a sha now so it won't break
> fix repocreator link

- docs/developer/editors.md
these aren't urgent but we should put them in
> Tweaks suggested by Clay

- docs/developer/graphql.md
Removed misplaced code block tag so page renders as intended
> GraphQL Page - Correct Formatting

- mkdocs.yml
Added an API Reference section to the nav with links to the auto-generated API docs.
> Added API reference section to navigation.

- docs/developer/commands.md
> Resolve invalid signature of helloWorldListener

- docs/developer/first_delivery.md
- mkdocs.yml
This is a tutorial @jessitron and I worked on. Its intent is to guide a completely new developer through the steps of setting up a goal and responding to pushes, both in Local Mode and Team Mode.
~~This is not quite ready for review yet! The instructions on configuring the SDM to post to Slack is still pending, and I haven't quite done a review of the text from start to finish. Still, were this to be merged as-is, I believe it's a good start to helping someone set up their first goals.~~
> First delivery tutorial

- docs/developer/sdm-concepts.md
This address' @jrday's feedback from https://github.com/atomist/docs/pull/286.
> Some minor tweaks

- docs/developer/commands.md
Updated code snippets to latest versions in atomist/sample
[auto-merge:on-check-success] [auto-merge-method:merge]
> Updated code snippets

- docs/developer/goal.md
> Add a link to container goals docs from Goals page

- docs/developer/aspects.md
Use proper indentation in code blocks.  Rename sample aspect to be
more accurate.  Add imports in code blocks.  Remove extraneous text.
> Clean up aspect developer doc

- docs/developer/commands.md
Add documentation for the updates in https://github.com/atomist/sdm/issues/793
> Using regex command intents
